# Travis CI integration -- https://travis-ci.org/troglobit/finit
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Use non-docker builds atm. to install libuEv and libite from source
#sudo: true

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "eOiuHs02lG2Uv146K9dMqucGTWUJFEhpz1oAtwe+kPrRXsXWc20hYMO+DSpMgD05vSvNeQA6p7h7LdRFQ+/g/Obj27TsOE+RKkUvRAtdwzxnKVyii9C/nmML8cFw7rIA0VS8O9mAkVYeyDxNDupBp3e9DPCibhKPvqCvioTnyy4="

addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/finit"
      description: "finit | Fast & Extensible init for Linux"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./configure"
    build_command:      "make"
    branch_pattern:     dev

install:
  - wget https://github.com/troglobit/libuev/releases/download/v1.4.0/libuev-1.4.0.tar.xz
  - wget https://github.com/troglobit/libite/releases/download/v1.5.0/libite-1.5.0.tar.xz
  - tar xf libuev-1.4.0.tar.xz
  - tar xf libite-1.5.0.tar.xz
  - (cd libuev-1.4.0 && ./configure --prefix=/tmp && make && make install-strip)
  - (cd libite-1.5.0 && ./configure --prefix=/tmp && make && make install-strip)

# Custom build script for the time being, no "make test" yet
script:
  - ./autogen.sh
  - PKG_CONFIG_PATH=/tmp/lib/pkgconfig ./configure --prefix=/tmp
  - make clean
  - make -j5 V=1
  - make install-strip
  - tree /tmp
  - ldd /tmp/sbin/finit
  - size /tmp/sbin/finit
  - size /tmp/sbin/initctl
  - size /tmp/sbin/reboot
  - LD_LIBRARY_PATH=/tmp/lib /tmp/sbin/initctl -h
