# Travis CI integration -- https://travis-ci.org/troglobit/finit
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "eOiuHs02lG2Uv146K9dMqucGTWUJFEhpz1oAtwe+kPrRXsXWc20hYMO+DSpMgD05vSvNeQA6p7h7LdRFQ+/g/Obj27TsOE+RKkUvRAtdwzxnKVyii9C/nmML8cFw7rIA0VS8O9mAkVYeyDxNDupBp3e9DPCibhKPvqCvioTnyy4="

addons:
  coverity_scan:
    project:
      name: "troglobit/finit"
      description: "finit | Fast & Extensible init for Linux"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./configure"
    build_command:      "make"
    branch_pattern:     dev

# Custom build script for the time being, no "make test" yet
script:
  - make distclean
  - ./configure
  - make
